### ISSUE TITLE
Ansible playboook fails

### ISSUE THREAD

**Issue by florian-ried** [pauldotyu/azure-virtual-desktop-terraform#3]
Amazing repo :) 

I want to use ansible 
I have met all the requirements 
The ansible playbook now fails with the following error:

![image](https://user-images.githubusercontent.com/95634472/149519377-e5162f74-15fa-4f66-aa77-566b70ae38d5.png)

I edit the nsgs to allow winrm via port 5986
Do you have any idea how I could solve the problem. 
Thank you so much!!! :)

**Comment by florian-ried** [comment]
![image](https://user-images.githubusercontent.com/95634472/149524634-1ebfd6d2-3230-4187-b89d-9697aefb7d96.png)

**Comment by florian-ried** [comment]
Firewall is open
I already ran this script on the client https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1
Unfortunately, I am not an expert in Ansible. But would love to use Ansible for rolling out session hosts

**Comment by pauldotyu** [comment]
@florian-ried - is your github running in a virtual network that has "line of sight" to your session host VM?
